import "./../../globals.css";
import DashboardSidebar from "@/Components/Common/DashboardSidebar";
import DashboardHeader from "@/Components/Common/DashboardHeader";


export const metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};

// not root layout this is main layout

export default function Layout({ children }) {
    return (
        <div className='flex items-start'>
            <DashboardSidebar />

            <div className="w-full">
                <DashboardHeader />
                <div className='p-5 lg:p-10'>
                    {children}
                </div>
            </div>
        </div>
    );
}
