import { Geist, Geist_Mono } from "next/font/google";
import "./../../globals.css";


export const metadata = {
    title: "Website Architecture",
    description: "Generated by create next app",
};

// not root layout this is main layout

export default function Layout({ children }) {
    return (
        <div>
            {children}
        </div>
    );
}
